### ISSUE TITLE
Cannot parse files where the default namespace is http://www.garmin.com/xmlschemas/TrackPointExtension/v2

### ISSUE THREAD

**Issue by KennethEvans** [tkrajina/gpxpy#242]
Normally the default namespace for a GPX file is http://www.topografix.com/GPX/1/1.

However it doesn't have to be.  Many of my files have the default namespace as http://www.garmin.com/xmlschemas/TrackPointExtension/v2

(TrackPointExtension/v2 is a common way to include heart rate data.)

It is not under my control how they do this, and I believe it is perfectly valid. These files open and parse correctly in all the other GPX applications I use. They open but don't parse correctly in gpxpy. In particular, no tracks are found.

The difference is
Ok Files:

`<gpx xmlns="http://www.topografix.com/GPX/1/1" xmlns:ns2="http://www.garmin.com/xmlschemas/TrackPointExtension/v2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.1" creator="Polar Access Manager" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">`

Not OK files:

`<ns2:gpx xmlns="http://www.garmin.com/xmlschemas/TrackPointExtension/v2" xmlns:ns2="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.1" creator="Polar Access Manager" xsi:schemaLocation="http://www.topografix.com/GPX/1/1 `

gpx.nsmap gives:
Ok Files:
```
Namespaces:
    defaultns: http://www.topografix.com/GPX/1/1
    ns2: http://www.garmin.com/xmlschemas/TrackPointExtension/v2
    xsi: http://www.w3.org/2001/XMLSchema-instance
```
Not Ok files:
```
Namespaces:
    defaultns: http://www.garmin.com/xmlschemas/TrackPointExtension/v2
    ns2: http://www.topografix.com/GPX/1/1
    xsi: http://www.w3.org/2001/XMLSchema-instanc
```
Notice xsi is not all there.

Sample files:
[gpxpy_issue.zip](https://github.com/tkrajina/gpxpy/files/7723968/gpxpy_issue.zip)
